config/routes.rb
require 'sidekiq/web'
Rails.application.routes.draw do
  resources :vehicles
  resources :spaces
  devise_for :users, controllers: { registrations: "registrations" }
	root to: 'home#index'
	resources :reservations
	authenticate :user, lambda { |u| u.admin? } do
		mount Sidekiq::Web => '/sidekiq'
	end
end

app/models/space.rb
class Space < ApplicationRecord
  belongs_to :user
  has_many :reservations
  has_one_attached :parking_spot_image
  geocoded_by :make_address
  after_validation :geocode, if: :needs_geocode?

  validates :state, :presence => true

  def make_address
    [address, city, state, zip.to_s].compact.reject(&:empty?).join(', ')
  end

  def has_valid_state
    states = ["AL", "AR", "AZ", "CA", "CO", "CT", "DE", "DC", "FL", "GA", "HI", "ID", "IL", "IN", "IA", "KS", "KY", "LA", "ME", "MD", "MA", "MI", "MN", "MS", "MO", "MT", "NE", "NV", "NH", "NJ", "NM", "NY", "NC", "ND", "OH", "OK", "OR", "PA", "RI", "SC", "SD", "TN", "TX", "UT", "VT", "VA", "WA", "WV", "WI", "WY"]
    unless states.include?(self.state)
      self.state = ""
      return false
    end
    return true
  end

  private

  def needs_geocode?
    return true if latitude.nil? && longitude.nil?
    return false
  end

end

app/controllers/spaces_controller.rb
class SpacesController < ApplicationController
  before_action :set_space, only: [:show, :edit, :update, :destroy]

  # GET /spaces
  # GET /spaces.json
  def index
    respond_to do |format|
      format.html do
        if current_user
          @spaces = Space.where(user_id: current_user.id)
        else
          @spaces = []
        end
      end
      format.json do
        coords = [params["lat"], params["lon"]]
        @spaces = Space.near(coords, 10)
        render json: @spaces
      end
    end
  end

  # GET /spaces/1
  # GET /spaces/1.json
  def show
  end

  # GET /spaces/new
  def new
    @space = Space.new
  end

  # GET /spaces/1/edit
  def edit
    @space.hourly_rate = @space.hourly_rate.to_f / 100
  end

  # POST /spaces
  # POST /spaces.json
  def create
    @space = Space.new(space_params.merge(user: current_user))
    if not @space.has_valid_state
        render :new
    else
        if @space.save
          redirect_to edit_space_path(@space), notice: 'Space was successfully created.'
        else
          render :new
        end
    end
  end



  # PATCH/PUT /spaces/1
  # PATCH/PUT /spaces/1.json
  def update
    valid_space_params = space_params
    days = ["avail_m", "avail_t", "avail_w", "avail_th", "avail_f","avail_sa", "avail_su"]
    unavail_days = days - valid_space_params.keys.select{|p| p.include?"avail"}
    avail_days = days - unavail_days
    unavail_days.each{ |day| valid_space_params[day] = false }
    avail_days.each {|day| valid_space_params[day] = true }
    valid_space_params[:hourly_rate] = (space_params[:hourly_rate].to_f * 100).to_i.to_s
    respond_to do |format|
      if @space.update(valid_space_params)
        format.html { redirect_to @space, notice: 'Space was successfully updated.' }
        format.json { render :show, status: :ok, location: @space }
      else
        format.html { render :edit }
        format.json { render json: @space.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /spaces/1
  # DELETE /spaces/1.json
  def destroy
    @space.destroy
    respond_to do |format|
      format.html { redirect_to spaces_url, notice: 'Space was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_space
      @space = Space.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def space_params
      params.require(:space).permit(:user_id, :address, :city, :state, :zip, :size, :avail_m, :avail_t, :avail_w, :avail_th, :avail_f, :avail_sa, :avail_su, :hourly_rate, :description, :parking_spot_image)
    end

end

app/helpers/spaces_helper.rb
module SpacesHelper
end

app/views/spaces/_form.html.erb
<%= form_for @space, :html => {:class => "ui form"} do |f| %>

  <% if space.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(space.errors.count, "error") %> prohibited this space from being saved:</h2>
      <ul>
        <% space.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

	<form class="ui form">
			<div class="field"> 
				<%=f.label :address, "Address" %>
				<%= f.text_field :address, {:style => "width: 20em;"} %>
			</div>
		<div class= "fields">
			<div class="field">
				<%= f.label :city, "City" %>
				<%= f.text_field :city, :style => "width: 10em;" %>
			</div>

			<div class="field">
				<%= f.label :state, "State" %>
				<%= f.text_field :state, :style => "width: 5em;" %>
			</div>

			<div class="field">
				<%= f.label :zip, "Zip Code" %>
				<%= f.text_field :zip, :style => "width: 10em;" %>
			</div>
		</div>
		
			<div class="field">
				<%= f.label :parking_spot_image, "Add a picture" %>
				<%= f.file_field :parking_spot_image %>
			</div>

			<div class="actions">
				<%= f.submit "List Space", class: 'ui button', :style => "width: 7em;" %>
				<%= f.submit "Cancel", class: 'ui button', :style => "width: 7em;" %>
			</div>
		</div> 
	</form> 

<% end %>

app/views/spaces/_form2.html.erb
<%= semantic_form_for @space, :html => {:class => "allformtwo ui form"} do |f| %>
		<h4> Availability </h4>
		<div class="everydaytoggilin">
			<div class="ui toggle checkbox <%= @space.avail_m ? 'checked' : '' %>">
				<%= f.label :Monday %>
				<input type="checkbox" name="space[avail_m]" id="space_avail_m" value="<%= @space.avail_m ? '1' : '0' %>" <%= @space.avail_m ? 'checked=""' : "" %>>
			</div>
				<br/>
			<div class="ui toggle checkbox <%= @space.avail_m ? 'checked' : '' %>">
				<%= f.label :Tuesday %>
				<input type="checkbox" name="space[avail_t]" id="space_avail_t" value="<%= @space.avail_t ? '1' : '0' %>" <%= @space.avail_t ? 'checked=""' : "" %>>
			</div>
				<br/>
			<div class="ui toggle checkbox <%= @space.avail_m ? 'checked' : '' %>">
				<%= f.label :Wednesday %>
					<input type="checkbox" name="space[avail_w]" id="space_avail_w" value="<%= @space.avail_w ? '1' : '0' %>" <%= @space.avail_w ? 'checked=""' : "" %>>
			</div>
				<br/>
			<div class="ui toggle checkbox <%= @space.avail_m ? 'checked' : '' %>">
				<%= f.label :Thursday %>
					<input type="checkbox" name="space[avail_th]" id="space_avail_th" value="<%= @space.avail_th ? '1' : '0' %>" <%= @space.avail_th ? 'checked=""' : "" %>>
			</div>
				<br/>
			<div class="ui toggle checkbox <%= @space.avail_m ? 'checked' : '' %>">
				<%= f.label :Friday %>
					<input type="checkbox" name="space[avail_f]" id="space_avail_f" value="<%= @space.avail_f ? '1' : '0' %>" <%= @space.avail_f ? 'checked=""' : "" %>>
			</div>
				<br/>
			<div class="ui toggle checkbox <%= @space.avail_m ? 'checked' : '' %>">
				<%= f.label :Saturday %>
					<input type="checkbox" name="space[avail_sa]" id="space_avail_sa" value="<%= @space.avail_sa ? '1' : '0' %>" <%= @space.avail_sa ? 'checked=""' : "" %>>
			</div>
				<br/>
			<div class="ui toggle checkbox <%= @space.avail_m ? 'checked' : '' %>">
				<%= f.label :Sunday %>
					<input type="checkbox" name="space[avail_su]" id="space_avail_su" value="<%= @space.avail_su ? '1' : '0' %>" <%= @space.avail_su ? 'checked=""' : "" %>>
			</div>
	</div>
	<div class="boom">
		<div class="field">
			<%= f.input :size, :html => {:class=>"ui radio checkbox"}, :as => :radio, :collection => ["Coupe", "Sedan", "Suv", "Truck / Van"] %>
		</div>
		<div class="field">
			<%= f.label :hourly_rate %>
			<%= f.text_field :hourly_rate, :as => :number %>
		</div>
		<div class="field">
			<%= f.label :description %>
			<%= f.text_field :description %>
		</div>
	</div>	

	<%= f.actions do %>
		<%= f.action :submit, :as => :button, :button_html => {class: 'ui submit button'}, :style => "width: 7em;" %>
		<%= f.action :reset, :as => :button, :button_html => {class: 'ui cancel button'}, :style => "width: 7em; " %>
		<li class="action button_action"><button class="ui cancel button" href="<%= root_path %>">Cancel</button></li>
	<% end %>


<% end %>

app/views/spaces/edit.html.erb
<h1>List a Space</h1>

<%= render 'form2', space: @space %>

app/views/spaces/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Spaces</h1>

<table>
  <thead>
		<tr>
				<th><h2>Address</h2></th>
				<th><h2>City</h2></th>
				<th><h2>State</h2></th>
				<th><h2>Zip</h2></th><br/>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @spaces.each do |space| %>
			<tr>
				<div class="space">
					<td><%= space.address %></td>
					<td><%= space.city %></td>
					<td><%= space.state %></td>
					<td><%= space.zip %></td>
				</div>
        <td><%= link_to 'Show', space %></td>
        <td><%= link_to 'Edit', edit_space_path(space) %></td>
        <td><%= link_to 'Delete', space, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Space', new_space_path %>

app/views/spaces/new.html.erb
<div class="container">
  <h1>List a Space</h1>
  <%= render 'form', space: @space %>
  
</div>

app/views/spaces/show.html.erb
<div class="yourspaceinfoshit">

	<p id="notice"><%= notice %></p>

	<h1> Your Space Info </h1>

	<p>
    <% if @space.parking_spot_image.attached?  %>
      <%= image_tag @space.parking_spot_image, height: 250 %>
    <% else %>
      <%= image_tag 'missing.png', height: 250 %>
    <% end %>
	</p>

	<%= hidden_field :User, @space.user %>

	<h2>Address</h2>
	
	<p>
		<%= @space.make_address %>
	</p>

	<table>
		<thead>
			<tr>
				<h2> Available </h2>
			</tr>
		</thead>
		<tbody>

			<td><% if @space.avail_m %>
						Monday
					<% else %> 
						<% style="display: none;" %>
					<% end %>
			</td>
			<td><% if @space.avail_t %>
						Tuesday
					<% else %> 
						<% style="display: none;" %>
					<% end %>
			</td>
			<td><% if @space.avail_w %>
						Wednesday
						<% else %> 
							<% style="display: none;" %>
					<% end %>
			</td>
			<td><% if @space.avail_th %>
						Thursday
					<% else %> 
						<% style="display: none;" %>
					<% end %>
			</td>
			<td><% if @space.avail_f %>
						Friday
					<% else %> 
						<% style="display: none;" %>
					<% end %>
			</td>
			<td><% if @space.avail_sa %>
						Saturday
					<% else %> 
						<% style="display: none;" %>
					<% end %>
					</td>
			<td><% if @space.avail_su %>
						Sunday
					<% else %> 
						<% style="display: none;" %>
					<% end %>
			</td>
		</tbody>
	</table>

	<p>
	<h2>Hourly Rate</h2> <%= format_currency @space.hourly_rate %>
	</p>

	<p>
	<h2>Size</h2>
	<%= @space.size %>
	</p>

	<p>
		<h2>Description</h2>
		<%= @space.description %>
	</p>

	<%= link_to 'Edit', edit_space_path(@space) %> 
	<%= link_to 'Back', spaces_path %>
</div>