config/routes.rb
require 'sidekiq/web'
Rails.application.routes.draw do
  resources :vehicles
  resources :spaces
  devise_for :users, controllers: { registrations: "registrations" }
	root to: 'home#index'
	resources :reservations
	authenticate :user, lambda { |u| u.admin? } do
		mount Sidekiq::Web => '/sidekiq'
	end
end

app/models/vehicle.rb
class Vehicle < ApplicationRecord
  belongs_to :user
  has_many :reservations
  validates :user_id, :make, :model, :color, :license_plate, :presence => true  
end

app/controllers/vehicles_controller.rb
class VehiclesController < ApplicationController
  before_action :set_vehicle, only: [:show, :edit, :update, :destroy]

  # GET /vehicles
  # GET /vehicles.json
  def index
    @vehicles = Vehicle.where(user_id: current_user.id)
  end

  # GET /vehicles/1
  # GET /vehicles/1.json
  def show
  end

  # GET /vehicles/new
  def new
    @vehicle = Vehicle.new
  end

  # GET /vehicles/1/edit
  def edit
  end

  # POST /vehicles
  # POST /vehicles.json
  def create
    @vehicle = Vehicle.new(vehicle_params.merge(user: current_user))

    respond_to do |format|
      if @vehicle.save
        format.html { redirect_to @vehicle, notice: 'Vehicle was successfully created.' }
        format.json { render :show, status: :created, location: @vehicle }
      else
        format.html { render :new }
        format.json { render json: @vehicle.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /vehicles/1
  # PATCH/PUT /vehicles/1.json
  def update
    respond_to do |format|
      if @vehicle.update(vehicle_params)
        format.html { redirect_to @vehicle, notice: 'Vehicle was successfully updated.' }
        format.json { render :show, status: :ok, location: @vehicle }
      else
        format.html { render :edit }
        format.json { render json: @vehicle.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /vehicles/1
  # DELETE /vehicles/1.json
  def destroy
    @vehicle.destroy
    respond_to do |format|
      format.html { redirect_to vehicles_url, notice: 'Vehicle was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_vehicle
      @vehicle = Vehicle.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def vehicle_params
      params.require(:vehicle).permit(:make, :model, :color, :license_plate)
    end
end

app/helpers/vehicles_helper.rb
module VehiclesHelper
end

app/views/vehicles/_form.html.erb
	<%= form_with(model: vehicle, local: true, class: "Wholeshit ui form") do |form| %>
		<% if vehicle.errors.any? %>
			<div id="error_explanation">
				<h2><%= pluralize(vehicle.errors.count, "error") %> prohibited this vehicle from being saved:</h2>

				<ul>
				<% vehicle.errors.full_messages.each do |message| %>
					<li><%= message %></li>
				<% end %>
				</ul>
			</div>
		<% end %>

		<div class="field">
			<%= form.label :make %>
			<%= form.text_field :make %>
		</div>

		<div class="field">
			<%= form.label :model %>
			<%= form.text_field :model %>
		</div>

		<div class="field">
			<%= form.label :color %>
			<%= form.text_field :color %>
		</div>

		<div class="field">
			<%= form.label :license_plate %>
			<%= form.text_field :license_plate %>
		</div>

		<div class="actions">
			<%= form.submit class:'ui button' %>
		</div>
	<% end %>

app/views/vehicles/edit.html.erb
<h1>Editing Vehicle</h1>

<%= render 'form', vehicle: @vehicle %>

<%= link_to 'Show', @vehicle %> |
<%= link_to 'Back', vehicles_path %>

app/views/vehicles/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Vehicles</h1>

<table>
  <thead>
    <tr>
      <th>Make</th>
      <th>Model</th>
      <th>Color</th>
      <th>License plate</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @vehicles.each do |vehicle| %>
      <tr>
        <td><%= vehicle.make %></td>
        <td><%= vehicle.model %></td>
        <td><%= vehicle.color %></td>
        <td><%= vehicle.license_plate %></td>
        <td><%= link_to 'Show', vehicle %></td>
        <td><%= link_to 'Edit', edit_vehicle_path(vehicle) %></td>
        <td><%= link_to 'Destroy', vehicle, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Vehicle', new_vehicle_path %>

app/views/vehicles/new.html.erb
<h1>New Vehicle</h1>

<%= render 'form', vehicle: @vehicle %>

<%= link_to 'Back', vehicles_path %>

app/views/vehicles/show.html.erb
<p id="notice"><%= notice %></p>
<h1>My Vehicle</h1>
<div class="showmethemoney">

	<div>
		<label class="ui header">Make:</label>
		<%= @vehicle.make %>
	</div>

<div>
		<label class="ui header">Model:</label>
	<%= @vehicle.model %>
</div>

<div>
		<label class="ui header">Color:</label>
		<%= @vehicle.color %>
</div>
<div>
		<label class="ui header">License plate:</label>
		<%= @vehicle.license_plate %>
</div>
	<div class="vehicle-buttons">
		<%= link_to 'Edit', edit_vehicle_path(@vehicle), class: "ui button" %> 
		<%= link_to 'Back', vehicles_path, class: "ui button" %>
		</div>
	</div>