config/routes.rb
require 'sidekiq/web'
Rails.application.routes.draw do
  resources :vehicles
  resources :spaces
  devise_for :users, controllers: { registrations: "registrations" }
	root to: 'home#index'
	resources :reservations
	authenticate :user, lambda { |u| u.admin? } do
		mount Sidekiq::Web => '/sidekiq'
	end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Peer Park</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/semantic-ui/2.3.3/semantic.min.css"/>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/semantic-ui/2.3.3/semantic.min.js"></script>
    <link href='https://api.tiles.mapbox.com/mapbox-gl-js/v0.47.0/mapbox-gl.css' rel='stylesheet' />
    <link rel='stylesheet' href='https://api.mapbox.com/mapbox-gl-js/plugins/mapbox-gl-geocoder/v2.3.0/mapbox-gl-geocoder.css' type='text/css' />
    <link href="https://fonts.googleapis.com/css?family=Hind+Madurai|Rubik:700|Varela+Round" rel="stylesheet" />

    <%= javascript_pack_tag 'app-bundle' %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
  </head>

  <body>
    <header class="navbar">
      
      <%#= link_to(image_tag("PP_Gray_Icon_Trans.png", root_path) %>

      <div class="nav">
        <div class="ui compact menu">
          <div class="ui simple dropdown item">
            <i class="bars icon"></i>
						<div class="menu">
						<% if user_signed_in? %>
              <%= link_to('Profile', edit_user_registration_path, class: "item") %>
              <%= link_to('Account History', reservations_path, class:"item") %>
                <%= link_to('Find a Space', root_path, class: "item") %>
                <%= link_to('List a Space', new_space_path, class: "item") %>
								<%= link_to('Logout', destroy_user_session_path, method: :delete, class: "item") %>
								<% else %>
								<%= link_to('Login', new_user_session_path, { class: 'item' })  %>
								<%= link_to('Sign up to List a Space', new_user_registration_path + '?list=true', { class: 'item' })  %>
								<%= link_to('Sign up to Find a Space', new_user_registration_path + '?list=false', { class: 'item'})  %>
							<% end %>
              </div>
            </div>
          </div>
        </div>
      </div>

      <a href="/"><%= image_tag("Peer_Park_Logo.png", :class => "peer-logo") %></a>

    </header>
		<div class="container">
		<p class="notice"><%= notice %></p>
		<p class="alert"><%= alert %></p>

		<%= yield %>
		<footer/>
</div>
  </body>
</html>

app/views/layouts/hello_world.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ReactOnRailsWithWebpacker</title>
    <%= csrf_meta_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>